### ISSUE TITLE
Regarding GTF file

### ISSUE THREAD

**Issue by varamhcu** [YumaIshigami/irscalc#1]
Thank you for the code. 

We are facing an issue with gtf file format. Can you kindly upload gtf file that is used for this program?

**Comment by YumaIshigami** [comment]
Thank you for raising this issue.
I edited the gtfbamcount.py file lines 70-73 so it can read GTF files that do not contain the gene_name attribute; it seems like the "gene_name" attribute was removed from the GTF file in the latest versions of S. pombe genome annotation.
The GTF file I used is downloadable from http://ftp.ensemblgenomes.org/pub/fungi/release-54/gtf/schizosaccharomyces_pombe/
I confirmed that the code no longer gives errors while reading GTF.

**Comment by varamhcu** [comment]
Thank you for the reply. I ran the updated Code. It didn't pop up any error. 

But the output is not printed in the file. Here I am attaching the results published on the terminal. Kindly check it and let us know if we are missing anything. 
**Code and result:**
Result printed on terminal after running: _python3 gtfbamcount.py YPD_KD1Aligned.out_sorted.bam FungiDB-53_CneoformansH99.gtf YPD_KD1_count.txt_
Lines read!
YPD_KD1Aligned.out_sorted.bam: 100.0%; checking:chrCP003822.1: 253681: utr_CNAG_02995-t26_1_2                   
YPD_KD1Aligned.out_sorted.bam count complete with 0.016666666666666666 minutes!

The output file contains only the header line. Let us know if we are making any mistakes.

**Comment by varamhcu** [comment]
The code is working after your modification. Your answer to another issue (number 2) worked. I am closing this thread. 

Thank you for the clarifications.
